name: Sign Executable

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  sign:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Cosign
        run: |
          curl -LO https://github.com/sigstore/cosign/releases/latest/download/cosign-windows-amd64.exe
          move cosign-windows-amd64.exe cosign.exe
          echo "$GITHUB_WORKSPACE" >> $GITHUB_PATH

      - name: Sign the Executable
        run: |
          cosign sign-blob --yes --output-signature CondoLoader.exe.sig --output-certificate CondoLoader.exe.crt CondoLoader.exe
        env:
          COSIGN_EXPERIMENTAL: true

      - name: Upload Signed Files
        uses: actions/upload-artifact@v3
        with:
          name: signed-files
          path: |
            CondoLoader.exe
            CondoLoader.exe.sig
            CondoLoader.exe.crt
